name: SDL2 i386 Dependency Tests

on: [push, pull_request, workflow_dispatch]

jobs:

  Ubuntu:
    strategy:
      fail-fast: false
      matrix:
        include:
          - deps: crossbuild-essential-i386 g++-i686-linux-gnu gcc-i686-linux-gnu
            tsk: Crossbuild
          - deps: g++-multilib gcc-multilib
            tsk: Multilib
          - deps: crossbuild-essential-i386 g++-i686-linux-gnu gcc-i686-linux-gnu libvulkan-dev libvulkan-dev:i386
            tsk: Crossbuild + Workaround
          - deps: g++-multilib gcc-multilib libvulkan-dev libvulkan-dev:i386
            tsk: Multilib + Workaround
    name: Ubuntu 24.04 / ${{ matrix.tsk }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Testing dependency installation resolution for SDL2 i386
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get --allow-change-held-packages --allow-downgrades --fix-broken --reinstall -y install build-essential clang g++ gcc git nasm pkg-config libsdl2-dev libsdl2-dev:i386 ${{ matrix.deps }}
